### ISSUE TITLE
about  map 83.35%

### ISSUE THREAD

**Issue by seeyourcell** [willard-yuan/pkbigdata-image-search#2]
”Convolutional Neural Network has been sucessfully applied to image classification, object detection, etc. However, It's not easy to apply it to duplicate search or object retrieval due to the difficult of data enhancement. Duplicate search can be used to many business applications such as searching the same clothes or shoes on Taobao, and I believe it has great application vulae. So after diving into image retrieval based on key point feature such as SIFT, I implement a prototype system based on bag of feature. The performance of the prototype image retrieval system works very well, and the mAP can be achieve to 83.35%. Moreover. I test it on 1500,000 clothes images, and the search result can be found here.“
the database is Oxford 105k？

**Comment by willard-yuan** [comment]
No, the dataset is a clothes dataset, and the images is from Taobao.
